# Generated by Django 5.0.4 on 2024-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poster_link', models.URLField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('Released_Year', models.IntegerField()),
                ('Certificate', models.CharField(max_length=100)),
                ('Runtime', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('IMDB_Rating', models.IntegerField()),
                ('Overview', models.CharField(max_length=1000)),
                ('Director', models.CharField(max_length=100)),
                ('Star1', models.CharField(max_length=100)),
                ('Star2', models.CharField(max_length=100)),
                ('Star3', models.CharField(max_length=100)),
                ('Star4', models.CharField(max_length=100)),
                ('Gross', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='moviesData',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('poster_link', models.URLField()),
                ('genre', models.ManyToManyField(related_name='movies_data', to='movies.genredata')),
            ],
        ),
    ]
