# Generated by Django 5.0.4 on 2024-05-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_Link', models.URLField(max_length=100)),
                ('Series_Title', models.CharField(max_length=100)),
                ('Released_Year', models.IntegerField()),
                ('Certificate', models.CharField(max_length=100)),
                ('Runtime', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('IMDB_Rating', models.IntegerField()),
                ('Overview', models.CharField(max_length=1000)),
                ('Director', models.CharField(max_length=100)),
                ('Star1', models.CharField(max_length=100)),
                ('Star2', models.CharField(max_length=100)),
                ('Star3', models.CharField(max_length=100)),
                ('Star4', models.CharField(max_length=100)),
                ('Gross', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
